name: C Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Compile C Programs
        run: |
          cd src; make all